- setup.md
As part of discussion in #136 
I add some further instructions to `setup.md` to initiate an RStudio project and move the downloaded data into the `data` subdirectory. 
This should enable us to remove any `setwd()`'s from each episode. Alternatively as part of the prerequisite of each lesson we can direct learners to the instructions for the RStudio project.
> Setup an RStudio Project

- _episodes_rmd/01-raster-structure.Rmd
links to the images not showing up should work now. I've removed the {{site.baseurl}} from the path
> solve path links in "Intro to Raster Data in R"

- _episodes_rmd/02-raster-plot.Rmd
This extends the ggplot-izing I started with #147 into episode 2, inline with goals outlined in #133 
I adopted the framework suggested in #155 for rendering hillshades 
* All plots constructed with `ggplot`
* Uses `dplyr` for any data manipulation inside a `data.frame()` object
> ggplot-ing episode 02

- _episodes_rmd/02-raster-plot.Rmd
- _episodes_rmd/03-raster-reproject-in-r.Rmd
- _episodes_rmd/04-raster-calculations-in-r.Rmd
This PR implements the following suggestions from https://github.com/datacarpentry/r-raster-vector-geospatial/issues/165:
[Episode 2](http://www.datacarpentry.org/r-raster-vector-geospatial/02-raster-plot/index.html)
[Episode 3](http://www.datacarpentry.org/r-raster-vector-geospatial/03-raster-reproject-in-r/index.html) 
[Episode 4](http://www.datacarpentry.org/r-raster-vector-geospatial/04-raster-calculations-in-r/index.html)
> Implement suggestions from #165

- _episodes_rmd/01-raster-structure.Rmd
Implements the following items from https://github.com/datacarpentry/r-raster-vector-geospatial/issues/165.
> more cleanup as suggested in #165

- _episodes_rmd/01-raster-structure.Rmd
- _episodes_rmd/02-raster-plot.Rmd
- _episodes_rmd/03-raster-reproject-in-r.Rmd
- _episodes_rmd/04-raster-calculations-in-r.Rmd
- _episodes_rmd/05-raster-multi-band-in-r.Rmd
- _episodes_rmd/06-vector-open-shapefile-in-r.Rmd
- _episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd
- _episodes_rmd/08-vector-plot-shapefiles-custom-legend.Rmd
- _episodes_rmd/09-vector-when-data-dont-line-up-crs.Rmd
- _episodes_rmd/10-vector-csv-to-shapefile-in-r.Rmd
- _episodes_rmd/11-vector-raster-integration.Rmd
- _episodes_rmd/12-time-series-raster.Rmd
- _episodes_rmd/13-plot-time-series-rasters-in-r.Rmd
- _episodes_rmd/14-extract-ndvi-from-rasters-in-r.Rmd
- index.md
This PR does a lot of things!
A) Structural: 
- Deletes header objects that are not used in the current template. 
- Moves information on authors to the index.md file so it will show up in the lesson homepage along with information about Maintainers. 
- Make libraries load silently where workshop learners will already have them loaded. 
- Moves pre-reqs to the lesson homepage and adds a pointer from the top of each episode to the lesson homepage. 
- Adds links to the introduction to R lesson and the Geospatial project organization lesson to the prereqs on the lesson homepage. 
- Adds time estimates for each episode. These were set at 10 minutes teaching, 0 minutes exercises for each episode. I increased this to 20 minutes teaching, 10 minutes exercises for each episode. This won't be …
> More cleanup

- _episodes_rmd/09-vector-when-data-dont-line-up-crs.Rmd
Per #133: This is a straight conversion of episode 9 plots to use `ggplot`. Also, following earlier conventions, explicitly calling `library(sf)` in the second code chunk.
An important remark for follow-up:
- `geom_sf` automatically transforms the CRS of additional layers (see second example in documentation [here](https://ggplot2.tidyverse.org/reference/ggsf.html)). Thus, the fourth plot shows the tower point in the correct location (it shouldn't appear on the map since each layer has a different CRS).
I will open an issue corresponding to this part of the episode.
> Convert episode 9 plotting to ggplot

- .travis.yml
Travis CI builds are failing and giving the error message below:
> This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid, and setguid executables. If you require sudo, add 'sudo: required' to your .travis.yml.
> add sudo: required

- _episodes_rmd/01-raster-structure.Rmd
- _episodes_rmd/09-vector-when-data-dont-line-up-crs.Rmd
Based on comments in https://github.com/datacarpentry/r-raster-vector-geospatial/issues/165. 
This PR does the following:
[Episode 9](https://datacarpentry.org/r-raster-vector-geospatial/09-vector-when-data-dont-line-up-crs/index.html)
> Cleanup to episode 9

- _episodes_rmd/11-vector-raster-integration.Rmd
This PR continues cleanup to episode 11 as discussed in https://github.com/datacarpentry/r-raster-vector-geospatial/issues/165. 
The following changes are included. 
[Episode 11](https://datacarpentry.org/r-raster-vector-geospatial/11-vector-raster-integration/index.html)
> Cleanup to episode 11

- _episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd
I have fixed some legend titles by adding a `labs()` call, but the issue where the legend patches are drawn as if the lines are polygons appears to be a `geom_sf` default, an issue addressed in Ep 8. Contrast with 
```
test <- as(stoneWall_HARV, 'Spatial')
test <- fortify(test)
ggplot() + 
geom_line(data = test, aes(x = long , y = lat, group = id, color = id), size = 1.5) +
coord_sf()
```
which draws the legend correctly by default. A separate PR will add some wording about this to Ep 8.
I have also thickened the lines on line plots so they'll show up better on projector screens etc. I've partially moved the discussion about setting line thickness up to the first occurrence as a result. I also altered some wording early in the lesson for accuracy.
> fix legend plotting issues

- _episodes_rmd/01-raster-structure.Rmd
- _episodes_rmd/03-raster-reproject-in-r.Rmd
- _episodes_rmd/04-raster-calculations-in-r.Rmd
- _episodes_rmd/05-raster-multi-band-in-r.Rmd
- _episodes_rmd/06-vector-open-shapefile-in-r.Rmd
- _episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd
- _episodes_rmd/08-vector-plot-shapefiles-custom-legend.Rmd
- _episodes_rmd/09-vector-when-data-dont-line-up-crs.Rmd
- _episodes_rmd/10-vector-csv-to-shapefile-in-r.Rmd
- _episodes_rmd/11-vector-raster-integration.Rmd
- _episodes_rmd/12-time-series-raster.Rmd
- _episodes_rmd/13-plot-time-series-rasters-in-r.Rmd
- _episodes_rmd/14-extract-ndvi-from-rasters-in-r.Rmd
For episodes 3 and 4:
* Adds key points
* Standardizes formatting
* Cleans up minor typos
For episode 5, the above plus:
* ggplotizes (closes https://github.com/datacarpentry/r-raster-vector-geospatial/issues/133)
> General cleanup

- _episodes_rmd/01-raster-structure.Rmd
- _episodes_rmd/03-raster-reproject-in-r.Rmd
- _episodes_rmd/04-raster-calculations-in-r.Rmd
- _episodes_rmd/05-raster-multi-band-in-r.Rmd
- _episodes_rmd/06-vector-open-shapefile-in-r.Rmd
- _episodes_rmd/09-vector-when-data-dont-line-up-crs.Rmd
- _episodes_rmd/10-vector-csv-to-shapefile-in-r.Rmd
- _episodes_rmd/14-extract-ndvi-from-rasters-in-r.Rmd
per issue #257 - the NEON website has been rearranged so links there were either 404'ing or redirecting. Also fixed a typo in lesson 1 and added a link to the PROJ documentation page in lesson 9.
> Updating links to external URLs

- _episodes_rmd/02-raster-plot.Rmd
Hello Erin, 
just a small bug fix. In the text ( and ] are mixed up. Here a small example:
```
> library(dplyr)
> custom_bins <- c(300, 350, 400, 450)
> mutate(data.frame(x = 397:403), fct_elevation_2 = cut(x, breaks = custom_bins))
x fct_elevation_2
1 397       (350,400]
2 398       (350,400]
3 399       (350,400]
4 400       (350,400]
5 401       (400,450]
6 402       (400,450]
7 403       (400,450]
```
Regards, 
Klaus
> mixed up ( ] in cut.

- _episodes_rmd/01-raster-structure.Rmd
This is a fix for the errors generated by the deprecated `geom_spatial` function. See #215
> replace geom_spatial calls in lesson 1, #215

- _episodes_rmd/02-raster-plot.Rmd
ranges in text are adapted to actual effect of code.
Also, space before units as recommended by International System of Units.
> make text reflect actual ranges used

- _episodes_rmd/01-raster-structure.Rmd
The default number of cells used is `1e+05` = 100,000, not 10,000.
> actually 100,000 cells by default

- _episodes_rmd/02-raster-plot.Rmd
More accurate text: using `terrain.colors(3)` does not give us the "first three colours", but it creates a 3-colour palette from the whole gradient.
> not the "three first colours"

- _episodes_rmd/01-raster-structure.Rmd
`point_HARV` -> `DSM_HARV`
"project string" -> "projection string"
add backticks around object name
"does this file has" -> "does this file have"
`ggplot` -> `ggplot2` when talking about the package, not the function
remove repeated warning message (already visible)
> typos, clearer wording and formatting, remove useless

- _episodes_rmd/02-raster-plot.Rmd
1) We're not turning the axes off, but the axis labels.
2) We can use the theme's hierarchy to turn both labels off in one argument.
> leaner code, more accurate sentence

- _episodes_rmd/02-raster-plot.Rmd
This is a more straightforward way of doing this, and minimizes the amount of new syntax that learners see
> Simplify summarize() call into just count()

- _episodes_rmd/11-vector-raster-integration.Rmd
Code at Although `CHM_HARV_sp` is defined in hidden code, it seems that the code in the text (line 152) meant to use `CHM_HARV` .  Doesn't run as-is because learners haven't defined `CHM_HARV_sp`.
> Fix undefined `CHM_HARV_sp` variable

- _episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd
There is an error in the solution, thanks to R's attempts to be helpful for us when working with na.omit with a factor variable. 
I explain the error below, and have fixed it (in as concise code as possible) above, in the pull request
----------
If we look at lines_HARV$BicyclesHo:
```
lines_HARV$BicyclesHo
[1] Bicycles and Horses Allowed     Bicycles and Horses Allowed     Bicycles and Horses Allowed    
[4] <NA>                            <NA>                            <NA>                           
[7] <NA>                            <NA>                            <NA>                           
[10] DO NOT SHOW ON REC MAP          Bicycles and Horses Allowed     Bicycles and Horses NOT ALLOWED
[13] Bicycles and Horses Allowed    
Levels: Bicycles and Horses Allowed Bicycles and …
```
> Critical: solution to challenge 1 in "Explore and Plot by Shapefile Attributes" is wrong

- _episodes_rmd/03-raster-reproject-in-r.Rmd
@rbavery and I taught a workshop with this lesson this week.
We found that the learners spent several minutes trying to type up this block of code, and double check parentheses and so on, only to find that the code example doesn't work.
I tried to remove unnecessary lines to get a minimal example that "should" work but doesn't, because of the resolution and projection.
It should also match the code for the final plot that is made after the res and crs fixes.
> Remove extra code in example that doesn't produce correct output

- _episodes_rmd/11-vector-raster-integration.Rmd
In episode 11 (Manipulate Raster Data in R), a couple shapefiles are loaded in a hidden code chunk to product a map, however, the output of `st_read()` is visible in the lesson, confusingly without any associated code. Use results="hide" in code chunk so this doesn't appear.
> ep. 11: results="hide" when loading sf data

- _episodes_rmd/11-vector-raster-integration.Rmd
Most raster package functions now handle sf objects without need for conversion to sp objects explicitly.
> No need to convert to sp prior to crop

- .travis.yml
based on this: https://travis-ci.org/github/datacarpentry/r-intro-geospatial/jobs/704467768#L946-L947 it seems that trusty is no longer supported by the PPA. I'm trying to see if bionic will work
> use bionic over trusty

- _episodes_rmd/09-vector-when-data-dont-line-up-crs.Rmd
Though this doesn't affect the rendering of the lesson, it affects how it's parsed for the translations.
> Fixes a multiline callout

- _episodes_rmd/03-raster-reproject-in-r.Rmd
In the introduction of the episode (Section: Raster Projection in R), the definitions of DTM and DSM do not match the ones on the figure. I'm correcting them to be consistent with GIS theory. I'm also adding a short definition of "hillshade". 
This contribution was previously discussed on an issue:  https://github.com/datacarpentry/r-raster-vector-geospatial/issues/331
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and …
> Definition of DTM and DSM + hillshade

- reference.md
Discussion in https://github.com/datacarpentry/datacarpentry.github.io/pull/531 identified a problem with broken links from https://datacarpentry.org/lessons/ to the reference and/or instructor notes pages for some lessons. This PR fixes the problem for the Reference page of this lesson, by unsetting the permalink on `reference.md`.
> Fix broken link from https://datacarpentry.org/lessons/

- _episodes_rmd/08-vector-plot-shapefiles-custom-legend.Rmd
This PR fixes the error in the second to last challenge of episode 8, which currently fails due to the use of `colour = NA` in `geom_sf()`, documented this error in #351. The modified R code all runs correctly on my machine, but I was unable to fully knit the `.Rmd` file, I'm guessing due to some knitr path issues/differences from the CI pipeline used to render the episode website.
While removing `colour = NA` reintroduces the black border on the dots, I've changed the dot fill scheme from blue and green to blue and orange to better distinguish between the two while the black border is present.
> fix challenge errors due to color = NA in geom_sf()

- _episodes_rmd/02-raster-plot.Rmd
X coordinates in UTM projections are known as eastings. This patch renames axis labels from 'Westing' to 'Easting'
> Correct name for UTM coordinates

- _episodes_rmd/01-raster-structure.Rmd
- _episodes_rmd/05-raster-multi-band-in-r.Rmd
When I was testing the transition for this lesson, I noticed five errors in the output that were not intended in episodes 1 and 5 along the lines of:
```
Error in FUN(X[[i]], ...): object 'HARV_RGB_Ortho.3' not found
```
It turns out, for a single layer from a tiff, the layer names default to "layer" and for a stack, the layer names are the filename with the layer number separated by an underscore
> fix errors in plotting raster and stack dataframes

- README.md
Trying to restyle the README for the new infrastructure.
@zkamvar Since there's no longer a Makefile, is the procedure for a local build to call `sandpaper::build_lesson`?
> towards workbench applicable readme

- episodes/01-raster-structure.Rmd
Lesson 1 updated by replacing calls to raster and rgdal packages with calls to terra package. 
#368 #363
> Lesson 1 updated by replacing calls to raster and rgdal packages

- episodes/05-raster-multi-band-in-r.Rmd
Episode 5 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363
> Episode 5 updated by replacing calls to raster and rgdal packages

- episodes/03-raster-reproject-in-r.Rmd
- episodes/04-raster-calculations-in-r.Rmd
Episode 4 updated by replacing calls to raster and rgdal packages with calls to terra package.
#368 #363
> Episode 4 updated by replacing calls to raster and rgdal packages with calls to terra package.

- episodes/07-vector-shapefile-attributes-in-r.Rmd
Episode 7 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363
> Episode 7 updated by replacing calls to raster and rgdal packages

- episodes/12-time-series-raster.Rmd
Episode 12 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363
> Episode 12 updated by replacing calls to raster and rgdal packages

- episodes/13-plot-time-series-rasters-in-r.Rmd
Episode 13 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363
> Episode 13 updated by replacing calls to raster and rgdal packages

- episodes/11-vector-raster-integration.Rmd
Episode 11 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363
> Episode 11 updated by replacing calls to raster and rgdal packages

- episodes/09-vector-when-data-dont-line-up-crs.Rmd
Episode 9 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363
> Episode 9 updated by replacing calls to raster and rgdal packages

- episodes/06-vector-open-shapefile-in-r.Rmd
- episodes/07-vector-shapefile-attributes-in-r.Rmd
- episodes/08-vector-plot-shapefiles-custom-legend.Rmd
- episodes/09-vector-when-data-dont-line-up-crs.Rmd
- episodes/10-vector-csv-to-shapefile-in-r.Rmd
- episodes/11-vector-raster-integration.Rmd
Edits are part of Issue #312 to update the terms “shapefile” and “simple features”
1. Replaced the term “shapefile” with "vector layer" where appropriate.
- Sometimes this was not a simple replacement as it needed to be made clear when ESRI shapefiles were the format of the vector layers, or when the term shapefile was being used as shorthand for a vector layer in R.
- It was not always possible to remove all references to shapefiles as sometimes the shapefile file format needed to be referenced – in those cases I explicitly called it an ESRI ‘Shapefile’ as it is a propriety format. Also, this is also the driver in the code mentions ESRI.
2. - It is sometimes unclear when we are referring to a “vector layer” or a “spatial object” in R. I have tried to make it clear and match with what was …
> Issue # 312 to update the terms “shapefile”

- episodes/01-raster-structure.Rmd
- instructors/instructor-notes.md
per issue #417 corrected the syntax of links to individual lessons in the instructor_notes.md file. 
the second half of them, from ep 7 thru 14, were all malformed.
> fixes #417 links in instructor notes

- episodes/03-raster-reproject-in-r.Rmd
on lines 321 and 328, original challenge says DTM_hill_SJER, 
but it should be DSM_hill_UTMZ18N_SJER (321) and DSM_hill_SJER_df(328) 
https://datacarpentry.org/r-raster-vector-geospatial/03-raster-reproject-in-r.html#challenge-reproject-then-plot-a-digital-terrain-model
> Typo in episode 3 Reproject and Plot Digital Terrain challenge

- episodes/07-vector-shapefile-attributes-in-r.Rmd
This PR removes an unnecessary NA filter and also an unnecessary cast to factor from  `Challenge: Plot Lines by Attribute` (episode `Explore and Plot by Vector Layer Attributes`) as reportec by @sstevens2 in issue #374. 
Fixes #374. Thanks to @sstevens2.
> Fixes #374. Thanks to @sstevens2

- episodes/09-vector-when-data-dont-line-up-crs.Rmd
When combining the state and country boundary, the lesson states the county boundary is supposed to be a slightly bolded outline, however, the state boundary shapefile is masking the country boundary so the bold outline does not show up. This would work if the country boundary layer had an alpha and was layered over the state boundary layer.
After making country border darker, adding alpha, and increasing size slightly: 
(Here's what it looks like in our fork:https://ucsb-dreamlab.github.io/r-raster-vector-geospatial/09-vector-when-data-dont-line-up-crs.html)
> Ep 9: Overlay error in episode between state and country boundary

- renv/activate.R
- renv/profiles/lesson-requirements/renv.lock
I've run the package update manually because the automated workflow was having trouble after the release of {renv} 1.0.0.
This brings in updates to 29 packages. Please wait for the output to run and then check for any new errors, warnings or surprising output changes.
I ran the following commands to update the cache with {renv} 1.0.2
```r
sandpaper::manage_deps()
sandpaper::update_cache()
```
```
- 29 packages have updates available.
- boot          [1.3-28 -> 1.3-28.1]
- bslib         [repo: RSPM -> CRAN; ver: 0.5.0 -> 0.5.1]
- classInt      [0.4-9 -> 0.4-10]
- cpp11         [repo: RSPM -> CRAN; ver: 0.4.4 -> 0.4.6]
- digest        [0.6.32 -> 0.6.33]
- dplyr         [1.1.2 -> 1.1.3]
- fontawesome   [0.5.1 -> 0.5.2]
- foreign       [0.8-82 -> 0.8-84]
- fs            [1.6.2 -> 1.6.3]
- …
```
> update 29 packages

- episodes/12-time-series-raster.Rmd
Replaces `gather()` with `pivot_longer()`.  `gather()` still works, but it is superseded, so better to teach `pivot_longer()` I think.
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries …
> Replace now superseded `gather()` with `pivot_longer()`

- episodes/12-time-series-raster.Rmd
It took me forever to figure out what the numbers in the filenames meant.  I only knew it was some kind of timeseries because of the title of the lesson.
This adds a sentence explaining that the numbers are julian day.
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would …
> Explain filenames

- episodes/02-raster-plot.Rmd
The count() function is an alias for groupby +summarize(n()).  It will group by the variable and count it in one function call so including the groupby function is redundant.
> Rm group by func call

- episodes/05-raster-multi-band-in-r.Rmd
There was a missing forward slash in the filepath listed for the challenge, "NODATA VALUES". Fixed.
> fixed missing forward slash in file path

- episodes/07-vector-shapefile-attributes-in-r.Rmd
- index.md
- r-raster-vector-geospatial.Rproj
Closes #462 and others issues that were confusing / out of date in episode 7. primarily the deprecation of size = ( replaced with linewidth = )
See the comments in #462. This PR also takes care of the maintainer list.
> Episode 7 updates for line sizes and other

- episodes/07-vector-shapefile-attributes-in-r.Rmd
a couple of oblique references to factors remained. I think I have eliminated them all now.
> removing final reference to factors

- episodes/05-raster-multi-band-in-r.Rmd
Reverts datacarpentry/r-raster-vector-geospatial#475
That was a change in episode 5 and the lesson build failed.
There was a note about a checkmd file also changing. 
I don't see why the 1 word change could prevent the repo from building.
> Revert "uses consistent carpentries terminology"

- episodes/05-raster-multi-band-in-r.Rmd
Remove `scale` argument from `plotRGB()` calls, as this argument currently is misleading (should not be larger than max value of bands within the raster).
Closes #476
> Fix plotRGB errors in Ep. 5

- episodes/06-vector-open-shapefile-in-r.Rmd
Add section to explain the mismatch between plot CRS and graticule CRS, and provide example on how to use CRS of first `geom_sf()` object to draw plot graticule
Closes #288
> Explain coordinate system mismatch

- episodes/06-vector-open-shapefile-in-r.Rmd
Add link to the Wikipedia entry for Simple Features, and statement about other software that implement the Simple Features Access standard, to provide context for students on why the `sf` package is used for vector data in these lessons
Closes #446
> Add explanation for use of `sf` package
