datacarpentry/r-raster-vector-geospatial

03-Multi-Band-Raster.Rmd

03-Multi-Band-Raster.Rmd: update yaml and text; add r code

---

01-Plot-Raster.Rmd

Rearrange lesson 01 code, add comments

---

00-Raster-Structure.Rmd
01-Plot-Raster.Rmd
02-Reproject-Raster.Rmd
03-Modify-Raster.Rmd

Propose re-arrangement of viewing attribute data prior to opening file to end and incorporating it into challenge. As was much of the tags/ attribute data wasn't yet introduced. 
I also think this section needs a brief discussion of why/ what projections, etc (e.g. only slightly more complicated than "how do you flatten an orange peel") and then links out for more information.  This could be the first time someone has used spatial data and the concepts aren't explained in a broader context.

Updates to Lessons 00 and 01

---

00-Raster-Structure.Rmd
01-Plot-Raster.Rmd
02-Reproject-Raster.Rmd
03-Modify-Raster.Rmd
04-Multi-Band-Raster.Rmd

I added to Challenge sections, rearranged the presentation of some of the notes/ bonus material, and added to alignment between lessons.

Lessons 03 and 04 Rearrangements and Edits

---

05-Time-Series-Raster.Rmd

Addition of "Unhealthy, senescent or dead vegetation" to last bit in Lesson 05.  All lessons now ready for a re-build and  posting!

Change to L05 from PR 37 comments

---

00-Raster-Structure.Rmd

Most of the changes are simple text edits or word smithing. I updated the UTM picture from wikipedia that got deleted/moved. I also moved some text out of figure captions because I felt it was oddly formatted or lost emphasis as a caption.
Great work putting this together, @lwasser & @mjones01!

00-Raster-Structure.Rmd: ZB review edits

---

01-Plot-Raster.Rmd

Mostly minor edits and adding a space after `#` in comment lines of code as per http://adv-r.had.co.nz/Style.html.
Couple notes:
- A 'method' means something very specific in programming languages: usually an object or function modification `object.method()`. `breaks` and `main` are function arguments as I've changed in the text.
- The `rainbows` color palette pops up oddly. I like the idea of demonstrating how color palettes differ, but I'd like to see a progression of plot map -> plot hill shade -> overlay map on hillshade, so that you can scroll back and see how they all fit together. Also, I wonder why it is not the hillshade that is overlayed on the map.

01-Plot-Raster.Rmd: ZB review edits

---

02-Reproject-Raster-In-R.Rmd

This looks great! Just minor edits.
What is going on with the 'Related Content: raster-data' at the bottom of the page? It doesn't seem to be in the `.Rmd`. It just animates (shrinks) when I click on it.

02-Reproject-Raster-In-R.Rmd: ZB review edits

---

00-open-a-shapefile.Rmd
01-shapefile-attributes.Rmd
02-plot-multiple-shapefiles-custom-legend.Rmd
03-when-vector-data-dont-line-up-CRS.Rmd
04-csv-to-shapefile-in-R.Rmd
05-vector-raster-integration-advanced.Rmd

Brought over lesson files from the vector lesson repo https://github.com/datacarpentry/NEON-R-Spatial-Vector

added files from Vector lesson to this repo

---

00-Raster-Structure.Rmd
01-Plot-Raster.Rmd
02-Reproject-Raster-In-R.Rmd
03-Raster-Calculations-In-R.Rmd
04-Multi-Band-Rasters-In-R.Rmd
05-Time-Series-Raster.Rmd
06-Plotting-Time-Series-Rasters-in-R.Rmd
07-Extract-NDVI-From-Rasters-in-R.Rmd
_posts/R/dc-spatial-raster/2016-01-07-SR00-Raster-Structure.md
_posts/R/dc-spatial-raster/2016-01-07-SR01-Plot-Raster.md
_posts/R/dc-spatial-raster/2016-01-07-SR02-Reproject-Raster-In-R.md
_posts/R/dc-spatial-raster/2016-01-07-SR03-Raster-Calculations-In-R.md
_posts/R/dc-spatial-raster/2016-01-07-SR04-Multi-Band-Rasters-In-R.md
_posts/R/dc-spatial-raster/2016-01-07-SR05-Time-Series-Raster.md
_posts/R/dc-spatial-raster/2016-01-07-SR06-Plotting-Time-Series-Rasters-in-R.md
_posts/R/dc-spatial-raster/2016-01-07-SR07-Extract-NDVI-From-Rasters-in-R.md

Bryn -> Brym in authors:

---

_episodes_rmd/01-raster-structure.Rmd
_episodes_rmd/02-raster-plot.Rmd
_episodes_rmd/03-raster-reproject-in-r.Rmd
_episodes_rmd/04-raster-calculations-in-r.Rmd
_episodes_rmd/05-raster-multi-band-in-r.Rmd
_episodes_rmd/06-vector-open-shapefile-in-r.Rmd
_episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd
_episodes_rmd/08-vector-plot-shapefiles-custom-legend.Rmd
_episodes_rmd/09-vector-when-data-dont-line-up-crs.Rmd
_episodes_rmd/10-vector-csv-to-shapefile-in-r.Rmd
_episodes_rmd/11-vector-raster-integration.Rmd
_episodes_rmd/13-plot-time-series-rasters-in-r.Rmd

This is the first stab at lessons 1-8. i used lintr in R because i can't get it to work in ATOM.
@jsta have you gotten it to actually fix the lint issues addressed before? i am new to using it. i'd love if it fixed things too... 
i also found a few space typos and replace `T` w `TRUE` because sometimes that can cause random errors in `R`! More later!

linting lessons 1-8

---

_episodes_rmd/01-raster-structure.Rmd

I made three corrections to the r markdown file of episode 1.
1. Defined UTM at first use. 
2. Fixed broken https: link to QGIS webpage. 
3. Fixed typo in challenge assignment.
I have not converted this to the .md file yet.

Holmquist-edits-to-EP1

---

_episodes/01-raster-structure.md
_episodes/02-raster-plot.md
_episodes/03-raster-reproject-in-r.md
_episodes/04-raster-calculations-in-r.md
_episodes/05-raster-multi-band-in-r.md
_episodes/06-vector-open-shapefile-in-r.md
_episodes/07-vector-shapefile-attributes-in-r.md
_episodes/08-vector-plot-shapefiles-custom-legend.md
_episodes/09-vector-when-data-dont-line-up-crs.md
_episodes/10-vector-csv-to-shapefile-in-r.md
_episodes/11-vector-raster-integration.md
_episodes/12-time-series-raster.md
_episodes/13-plot-time-series-rasters-in-r.md
_episodes/14-extract-ndvi-from-rasters-in-r.md

Hi,
I have updated {: .r} to {: .language-r} in the lesson.

Updating {: .language-r}

---

.gitattributes
_episodes/01-raster-structure.md

This PR adds a `.gitattributes` file to force Github to set the repo language as `R`.

force language detection to R

---

_episodes_rmd/01-raster-structure.Rmd

updated the link for NEON AOP LiDAR sensor data to link to new webpage. This was brought up by issue #125

Update link #125 for 01-raster-structure.Rmd

---

setup.md

the file `setup.md` should contain all packages we need to run through a lesson 
I have updated it with two extra packages that were not previously there:
* rasterVis
* rgdal
I also corrected a CRAN link on the raster line which was incorrectly pointing to the sf page.

Add more R packages to setup.md

---

README.md
index.md

Added the new lesson maintainers to README

Add new maintainers to README

---

_episodes_rmd/01-raster-structure.Rmd

"/images/..." corrected to point an higher level folder "../images/...

correction of paths for #130

---

DESCRIPTION
_episodes_rmd/01-raster-structure.Rmd

This is a modification of #147

ggplot rendering for episode 01

---

setup.md

PR needed to be against master instead of gh-pages.

add line break after yaml

---

_episodes_rmd/06-vector-open-shapefile-in-r.Rmd

Fixes https://github.com/datacarpentry/r-raster-vector-geospatial/issues/96

remove unhelpful hint in exercise

---

_episodes_rmd/06-vector-open-shapefile-in-r.Rmd
_episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd
_episodes_rmd/08-vector-plot-shapefiles-custom-legend.Rmd

The changes in #179 were reviewed, accepted, and merged but do not appear in the current lesson because of hijinks with the Travis CI build. This PR will redo those changes.

Redo missing changes

---

index.md

Replaces https://github.com/datacarpentry/r-raster-vector-geospatial/pull/196

moves pointer to data

---

_episodes_rmd/01-raster-structure.Rmd

This should handle the API changes with the new version.

fixes for ggspatial update

---

_episodes_rmd/13-plot-time-series-rasters-in-r.Rmd
_episodes_rmd/14-extract-ndvi-from-rasters-in-r.Rmd

This PR makes the following changes to episodes 13 and 14.
[Episode 13](https://datacarpentry.org/r-raster-vector-geospatial/13-plot-time-series-rasters-in-r/index.html)
[Episode 14](https://datacarpentry.org/r-raster-vector-geospatial/14-extract-ndvi-from-rasters-in-r/index.html)

Cleanup to last two episodes

---

_episodes_rmd/08-vector-plot-shapefiles-custom-legend.Rmd

Note that the plot code in Challenge: Plot Polygon by Attribute requires complex overrides to get the legend looking right - this may be tricky to explain, tbh I'm not sure I could explain it to myself D:

fixing plots as for ep 7

---

_episodes_rmd/01-raster-structure.Rmd

I don't think we need to specify `raster::as.data.frame` here. `DSM_HARV` is of the correct class, and the method dispatch will call the correct function.

remove mention of using raster::

---

_episodes_rmd/01-raster-structure.Rmd

Fixes https://github.com/datacarpentry/r-raster-vector-geospatial/issues/239

Remove callout box about ggspatial

---

_episodes_rmd/01-raster-structure.Rmd
_episodes_rmd/02-raster-plot.Rmd
_episodes_rmd/03-raster-reproject-in-r.Rmd
_episodes_rmd/04-raster-calculations-in-r.Rmd
_episodes_rmd/05-raster-multi-band-in-r.Rmd
_episodes_rmd/06-vector-open-shapefile-in-r.Rmd
_episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd
_episodes_rmd/08-vector-plot-shapefiles-custom-legend.Rmd
_episodes_rmd/09-vector-when-data-dont-line-up-crs.Rmd
_episodes_rmd/11-vector-raster-integration.Rmd
_episodes_rmd/12-time-series-raster.Rmd
_episodes_rmd/13-plot-time-series-rasters-in-r.Rmd

Fixes https://github.com/datacarpentry/r-raster-vector-geospatial/issues/240

Add coord_equal() to all spatial plots

---

_episodes_rmd/01-raster-structure.Rmd

fixed typos in line 43, 64, 196, and 448.  Also changed wording in line 463
Please delete the text below before submitting your contribution. 
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  
---

fixed typos in01-raster-structure.Rmd

---

_episodes_rmd/01-raster-structure.Rmd

Remove useless line as we already have the exact same data.frame, and we might want to reuse the raster object later on.

keep original raster object, we alread have a df

---

_episodes_rmd/02-raster-plot.Rmd

stray words, and spacing around `=` as in the rest of the code

typos, spaces

---

_episodes_rmd/01-raster-structure.Rmd

Same as https://github.com/datacarpentry/genomics-r-intro/pull/37 ;-)

Canonicalize CRAN links

---

_episodes_rmd/06-vector-open-shapefile-in-r.Rmd

remove obsolete data tip, #289

---

_episodes_rmd/01-raster-structure.Rmd
_episodes_rmd/05-raster-multi-band-in-r.Rmd
_episodes_rmd/06-vector-open-shapefile-in-r.Rmd
_episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd
_episodes_rmd/12-time-series-raster.Rmd

fix broken links, closes #291

---

_episodes_rmd/01-raster-structure.Rmd
_episodes_rmd/02-raster-plot.Rmd
_episodes_rmd/03-raster-reproject-in-r.Rmd
_episodes_rmd/04-raster-calculations-in-r.Rmd
_episodes_rmd/05-raster-multi-band-in-r.Rmd
_episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd
_episodes_rmd/08-vector-plot-shapefiles-custom-legend.Rmd
_episodes_rmd/09-vector-when-data-dont-line-up-crs.Rmd
_episodes_rmd/10-vector-csv-to-shapefile-in-r.Rmd
_episodes_rmd/11-vector-raster-integration.Rmd
_episodes_rmd/12-time-series-raster.Rmd
_episodes_rmd/13-plot-time-series-rasters-in-r.Rmd
_episodes_rmd/14-extract-ndvi-from-rasters-in-r.Rmd

increase lesson timings, #293

---

_episodes_rmd/01-raster-structure.Rmd

Error in rendering plot on website under "Find bad data values" in lesson 1. Problem arises from misnamed reference to column in the data frame.

find bad data values plot error in episode 1

---

_episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd

remove simple adjective #320

---

_episodes_rmd/01-raster-structure.Rmd

See load dplyr and ggplot2 packages

load dplyr and ggplot2 packages

---

_episodes_rmd/03-raster-reproject-in-r.Rmd

res(DTM_hill_HARV) should be res(DTM_HARV)
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution …

Fix mistake in resolution comparison

---

_episodes_rmd/03-raster-reproject-in-r.Rmd

I reordered notes according to comments in pr #272 to make it read a little smoother in this section. @jsta could you confirm that these changes look good?

added notes to follow up with conversation of pr #272

---

_episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd

This contribution is part of the Core Team accessibility hackathon to add alt-text to images across our lessons. Please feel free to improve upon these suggestions as desired!

add alt text for figures

---

CITATION
README.md
index.md

jsta name fix

---

_episodes_rmd/07-vector-shapefile-attributes-in-r.Rmd

The challenge suggests using the fill colour but the answer shows the lines being coloured.
I’ve taken the easy solution to just change the challenge, but if desired, could rewrite the R code to change the fill colour of the states.
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and …

Make the challenge with States match the answer

---

.github/PULL_REQUEST_TEMPLATE.md
_includes/check_transition_variables.html
_includes/javascript.html
_includes/lesson_footer.html
_includes/life_cycle.html
_includes/navbar.html
_layouts/base.html
assets/css/lesson.scss
bin/boilerplate/_config.yml

This brings in updates from the styles repository ahead of The Workbench Beta Phase

update styles 2022 10

---

_episodes_rmd/12-time-series-raster.Rmd

I made this code look nicer using mutate(), case_when(), and select() from dplyr. This was marked as a "good first issue" in Issue #227 , so I thought I would tackle it.

Cleaning up some RGB value manipulation in Episode 12

---

config.yaml

I accidentally left the old URL, which affects the "Edit this page" links 🙈

fix URL in config

---

episodes/03-raster-reproject-in-r.Rmd

Lesson 3 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363

Lesson 3 updated by replacing calls to raster and rgdal packages.

---

episodes/06-vector-open-shapefile-in-r.Rmd

Episode 6 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363

Episode 6 updated by replacing calls to raster and rgdal packages.

---

episodes/08-vector-plot-shapefiles-custom-legend.Rmd

Episode 8 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363

Episode 8 updated by replacing calls to raster and rgdal packages

---

episodes/10-vector-csv-to-shapefile-in-r.Rmd

Episode 10 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363

Episode 10 updated by replacing calls to raster and rgdal packages

---

episodes/14-extract-ndvi-from-rasters-in-r.Rmd

Episode 14 updated by replacing calls to raster and rgdal packages with calls to terra package. #368 #363

Episode 14 updated by replacing calls to raster and rgdal packages

---

episodes/03-raster-reproject-in-r.Rmd

fix episode 3 reversion according to [these instructions](https://github.com/carpentries/sandpaper/issues/411#issuecomment-1479575067) by @zkamvar

fix episode 3 reversion

---

episodes/01-raster-structure.Rmd

Adjusted fenced divs to fix display issues in plotting tip and challenges.

Adjusted fenced divs to fix display issues

---

episodes/03-raster-reproject-in-r.Rmd

This addresses the accidental reversion that happened in https://github.com/datacarpentry/r-raster-vector-geospatial/pull/387
see https://github.com/carpentries/sandpaper/issues/411#issuecomment-1480169622 for details

fix episode 3 revision

---

episodes/05-raster-multi-band-in-r.Rmd

fixed typos: Capitalization error in title and wrong package name listed

---

episodes/05-raster-multi-band-in-r.Rmd

uses consistent carpentries terminology
